pull request after one year (#340)
* add possiility of default values

* fix wrong path

* fix missing libs

* add tolerance for integer values

* change saving format from register read

* improve help message

* improve help message

* fix issue 330

* fix issue 330

* fix issue 330, when stil compiler not available

* fix issue 325: loading pattern in a testbench

* fix exception if tester have no run_pattern

* fix issue 329: Test Program Wizard->Pattern->Signal To Channel there is no selection of No assignment for Signal Name to Channel Number

* fix no return value from run_pattern

* add generated code if  patterns are defined

* add generated code if  patterns are defined

* remove double __init__

* fix warning in spyder editor

* add workaround for issue 168 in the autoscripts: The spyder breakpoints doesnt work

* add column for pattern path and copy this pattern to the pattern directory

* activate mapping_save only when test contest defined

* fix error if a name occurs more than once

* restore invalid issue 330

* restore invalid issue 330

* fix issue 329: values were too small by 1

* add functions

* fix verilog comment lines

* avoid eception if communication to DUT is no correct

* avoid eception if communication to DUT is no correct

* add memory array in result

* add register read if cache is None

* add ability to prevent pattern loading

* improve interface to the testerconfig file

* improve reading from text-files to memory mapping

* add logger outputs

* fix forget breakpoint :-(

* display warning if you use a configuration file with name extension

* add verilog read

* fix pep8 issues

* fix exception if setup not available

* update to spyder version 5.5.1

* improve readtxtMemFile with flag rawdata

* clear use of libs

* add hardware and base to compiled pattern_output files

* fix wrong find from _

* change variable name

* change ip from broker_host

* fix error with np.Inf

* add widget for pattern_import in hardwaresetups

* fix if index not available

* fix wrong colour and items from pattern import menu

* Update CICD.yml

Signed-off-by: Christian Jung <christian.jung@tdk.com>

* fix exception in pytest test_smoke_test.py

* update spyder version to 5.5.5

* fix tests/test_masterapp.py:61: ValidationError

* tests/test_masterapp_usersettings.py:53: ValidationError

* fix AttributeError: np.NaN was removed in the NumPy 2.0 release. Use np.nan instead

* fix migrate_check/test_migrate_check.py:93: AssertionError

* fix test_integrate.py:281: AssertionError

* fix assertion: Logger object has no attribute info

* fix AttributeError: np.Inf was removed in the NumPy 2.0 release. Use np.inf instead.

* fix TypeError: Client.__init__() got an unexpected keyword argument client_id

* fix try with an old version from aiomqtt: Client.__init__() got an unexpected keyword argument

* fix try with an old version from aiomqtt: Client.__init__() got an unexpected keyword argument

* fix try with an old version from aiomqtt: Client.__init__() got an unexpected keyword argument

* fix comment

---------

Signed-off-by: Christian Jung <christian.jung@tdk.com>